# Configuración de Wrangler para Contact Form Worker
name = "contact-form-worker"
main = "src/index.js"
compatibility_date = "2024-01-15"

# Variables de entorno públicas (development)
[vars]
ENVIRONMENT = "development"
CORS_ORIGIN = "http://localhost:4321"
RATE_LIMIT_MAX = 10
RATE_LIMIT_WINDOW = 3600

# Entorno de staging
[env.staging]
name = "contact-form-worker-staging"
vars = { 
  ENVIRONMENT = "staging",
  CORS_ORIGIN = "https://staging.ncs-psicologa.com",
  RATE_LIMIT_MAX = 10,
  RATE_LIMIT_WINDOW = 3600
}

# Entorno de producción
[env.production]
name = "contact-form-worker"
vars = { 
  ENVIRONMENT = "production",
  CORS_ORIGIN = "https://ncs-psicologa.com",
  RATE_LIMIT_MAX = 10,
  RATE_LIMIT_WINDOW = 3600
}

# ============================================
# SECRETS (configurar con wrangler secret put)
# ============================================
# Ejecutar estos comandos para configurar secrets:
#
# wrangler secret put RESEND_API_KEY
# wrangler secret put SUPABASE_URL
# wrangler secret put SUPABASE_SERVICE_ROLE_KEY
# wrangler secret put CONTACT_EMAIL_TO
# wrangler secret put CONTACT_EMAIL_FROM
#
# Para staging:
# wrangler secret put RESEND_API_KEY --env staging
# wrangler secret put SUPABASE_URL --env staging
# ... etc
#
# Para production:
# wrangler secret put RESEND_API_KEY --env production
# wrangler secret put SUPABASE_URL --env production
# ... etc

