name = "ncs-deploy"
main = "ncs-deploy-pure.js"
compatibility_date = "2024-09-10"

# Variables de entorno normales
[vars]
GITHUB_REPO = "jumidi/ncs"

# Variables secretas (configurar con: wrangler secret put SECRET_NAME)
# GITHUB_TOKEN - Personal Access Token con scope 'repo'
# WEBHOOK_SECRET - Secreto compartido con Sanity (opcional)

# Configuración de logging
[observers]
[observers.logs]
enabled = true

# Configuración de CORS
[[routes]]
pattern = "*"
custom_domain = false
