name = "ncs"
main = "static-site-worker.js"
compatibility_date = "2024-09-18"

# Configuración para sitio web estático
[site]
bucket = "../web/dist"

# Variables de entorno
[vars]
SITE_NAME = "NCS Psicóloga Zaragoza"
SITE_URL = "https://ncs.jum1d1460.com"
