name = "sanity-webhook-dispatcher"
main = "sanity-webhook-dispatcher.js"
compatibility_date = "2024-09-10"

# Variables de entorno (configurar en Cloudflare Dashboard)
[vars]
# GITHUB_TOKEN - Personal Access Token con scope 'repo'
# GITHUB_REPO - Formato 'owner/repo' (ej. 'jumidi/ncs')
# WEBHOOK_SECRET - Secreto compartido con Sanity (opcional)

# Configuración de logging
[observers]
[observers.logs]
enabled = true

# Configuración de CORS
[[routes]]
pattern = "*"
custom_domain = false
